### ISSUE TITLE
Adjektiv har ikkje trebokstavsgrensa for samansetjing ⇒ mystiske forslag

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-fao#1]
Jf dette:

![Bilde 27 08 2020 klokken 09 26](https://user-images.githubusercontent.com/1255285/91399980-98acb980-e847-11ea-807d-c203e7518ff2.jpg)

Fyrste og tredje forslag er ok, det andre ikkje. Analysen av det er:

```sh
echo eygaóð | hfst-lookup -q src/analyser-gt-norm.hfstol 
eygaóð	eyga+N+Neu+Sg+Gen+Cmp#óður+A+Fem+Sg+Nom+Indef
eygaóð	eyga+N+Neu+Sg+Gen+Cmp#óður+A+Neu+Pl+Acc+Indef
eygaóð	eyga+N+Neu+Sg+Gen+Cmp#óður+A+Neu+Pl+Nom+Indef
```

Det er opplagt ikkje ei samansetjing me vil ha. @Trondtr - noko du kan sjå på? @fo-raettstavari - synspunkt?

**Comment by fo-raettstavari** [comment]
Nei eg eri samdur. Lat okkum heldur leksikalisera tey.

Forrestin Sjur, sært tú afturmeldingarnar, sum eg havi sent frá stava@setur.fo<mailto:stava@setur.fo>? Eg skuldi skriva tína adressu manuelt, og eg havi kanska skrivað skeift.


Fra: Sjur Moshagen <notifications@github.com>
Sendt: 27. august 2020 07:33
Til: giellalt/lang-fao <lang-fao@noreply.github.com>
Cc: Heðin Jákupsson <HedinJ@setur.fo>; Mention <mention@noreply.github.com>
Emne: [giellalt/lang-fao] Adjektiv har ikkje trebokstavsgrensa for samansetjing ⇒ mystiske forslag (#1)


Jf dette:

[Billede fjernet af afsender. Bilde 27 08 2020 klokken 09 26]<https://user-images.githubusercontent.com/1255285/91399980-98acb980-e847-11ea-807d-c203e7518ff2.jpg>

Fyrste og tredje forslag er ok, det andre ikkje. Analysen av det er:

echo eygaóð | hfst-lookup -q src/analyser-gt-norm.hfstol



eygaóð  eyga+N+Neu+Sg+Gen+Cmp#óður+A+Fem+Sg+Nom+Indef



eygaóð  eyga+N+Neu+Sg+Gen+Cmp#óður+A+Neu+Pl+Acc+Indef



eygaóð  eyga+N+Neu+Sg+Gen+Cmp#óður+A+Neu+Pl+Nom+Indef

Det er opplagt ikkje ei samansetjing me vil ha. @Trondtr<https://github.com/Trondtr> - noko du kan sjå på? @fo-raettstavari<https://github.com/fo-raettstavari> - synspunkt?

**Comment by Trondtr** [comment]
Det stemmer: CmpNP-taggane manglar på adjektivsida. Eg skal leggje dei til.

**Comment by Trondtr** [comment]
hfst-ospell -S -n 5 tools/spellcheckers/fo.zhfst 
eygaóð
"eygaóð" is NOT in the lexicon:
Corrections for "eygaóð":
eygað    20.548828
eygagóð    23.949219
eygagóði    24.949421
eygagóðu    24.949421

Det ser ut til at dette er i boks no.

**Comment by Trondtr** [comment]
Og her er det opprinnelege ordet:

"eygaðð" is NOT in the lexicon:
Corrections for "eygaðð":
eygað    16.548828
eykað    23.950195
eyga    25.814453

**Comment by snomos** [comment]
@Trondtr eg ser at du både har laga eit eige leksikon og lagt på `+CmpNP/None`. Dette er delvis dobbelt opp. `+CmpNP/None` er i seg sjølv nok til å stoppa samansetjingar for eit ord. Det å ha eit eige leksikon er kraftigare skyts, og gjer det vanskelegare å gjera unnatak: ordet må flyttast istf berre å få ein (eller fleire) andre `+CmpNP/`-tagg(ar).

**Comment by Trondtr** [comment]
La oss halde fram denne diskusjonen, men ikkje som ein bug. Den opprinnelege meldinga var at 3-bokstavgrensa ikkje var lagt til, no er ho det. Eg lukkar lusmeldinga, så held vi fram diskusjonen om CmpNP i normative og deskriptive fst-ar i andre fora.
