### ISSUE TITLE
./configure --enable-tokenisers gives error

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-fao#3]
config.status: error: cannot find input file: `tools/tokenisers/Makefile.in'

**Comment by snomos** [comment]
Eg er ikkje i stand til å reprodusera. Har du prøvd å køyra `./autogen.sh` fyrst?

**Comment by albbas** [comment]
Det fungerte nå, kjørte:
cd $GTCORE
make
cd ../lang-fao
git reset --hard
git clean -fx
git pull --rebase
./autogen.sh
./configure --enable-tokenisers
make
