### ISSUE TITLE
... backtracking around the substring ... but ... no analyses.

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-fao#6]
There are many error messages like:
`Warning: The analysis of "<t.d.>" has backtracking around the substring "<t.d>", but that substring has no analyses.`
The lexc lexicon structure is:

```
t.d ab-dot-trab ;

LEXICON ab-dot-trab ab-dot-noun-trab ; ! assuming noun

LEXICON ab-dot-noun-trab    +ABBR+Gram/TAbbr:    ab-dot-noun ;

LEXICON ab-dot-noun   !!= * **@CODE@**  This is the lexicon for abbrs that must have a period.
+N+Abbr:  dot-infl ;

LEXICON dot-infl   !!= * **@CODE@**
!!= **@LEXNAME@**
DOT ;

LEXICON DOT   !!= * **@CODE@** - Adds the dot to dotted abbreviations.
!!= **@LEXNAME@**

 +Use/-PMatch:%. # ; ! We need the dot here for regular fsts
! Split the abbr + full stop in two segments, but only when using pmatch:
< "@P.Pmatch.Loc@" {.} "+CLB":0 "+Use/PMatch":0 > # ;
! Make a regular ABBR analysis AND backtrack to find alternative analyses:
< "+Use/PMatch":0 "@P.Pmatch.Backtrack@" 0:%. > # ;
```
The error message is correct: "t.d" (the version without final dot) indeed has no analysis. Now, the situation is:

Either the error message gives rise to concern, and we should change the fst (although I do not see the problem)
Or everything is ok, in which case I suggest we get rid of the error message.

**Comment by snomos** [comment]
This is as it must be. See the comments and documentation added to the code.
